@startuml er-diagram

class "Client" as Client {
  - id
  - phone
  - status
  - name
  - sex
}

class "LoyalityEvents" as LoyalityEvents {
  - id
  - client_id
  - name
  - type
  - start_date
  - total
}

class "AdditionalInformation" as AdditionalInformation {
  - client_id
  - characteristic
  - value
}

class "BonusAccounts" as BonusAccounts {
  - id
  - client_id
  - status
}

class "BonusTransactions" as BonusTransactions {
  - account_id
  - client_id
  - datetime
  - type
  - basis
  - total
}

BonusAccounts }|--|| Client
BonusTransactions }o--|| BonusAccounts
AdditionalInformation }o--o{ Client
LoyalityEvents }o--|| Client

@enduml